import numpy as np
array = np.array([9, 9, 8, 7, 7, 6, 5])
print("Array is : ", array)
print()
arrayAppend = np.append(array, [2, 3])
print("Array after append() is : ", arrayAppend)
print()
arrayInsert = np.insert(array, 5, 2)
print("Array after insert() is : ", arrayInsert)
print()
arrayDelete = np.delete(array, 4)
print("Array after insert() is : ", arrayDelete)
print()
arrayUnique = np.unique(array)
print("Array after unique() is : ", arrayUnique)
print()
arraySort = np.sort(array)
print("Array after sort() is : ", arraySort)
print()